// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
dotenv.config({ path: '../../apps/web/.env' });
import { defineConfig } from "prisma/config";

try {
  loadEnvFile(resolve(__dirname, "../../.env"));
} catch {
  // fallback: try local .env if root one not found
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
